language: node_js
node_js:
  - 6
script: node_modules/.bin/intern-client config=tests/intern && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  email:
    - brendanlacroix@gmail.com